---
abstract: Exporting
author:
  - 'Robert Acock <thisusedtobeanemail@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Import-Export
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  perl: 5.006
version: 0.04
